version: 2
jobs:
  deploy:
    machine:
      enabled: true
    working_directory: ~/out
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "65:a5:7d:c0:be:3b:90:f9:53:f1:ef:da:d3:a4:2b:ae" #上記メモったハッシュを指定
      - run: rsync -r -vc ./out ${SSH_USER}@${SSH_HOST}:/var/www/html/circleci/next_test0/
 
workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master